<?php

$weatherIndex = array("쾌청","맑음","흐림","안개","바람","폭풍","비","폭우","번개","뇌우","모래먼지","모래폭풍","열파","작열파","눈","눈보라","요마의 안개","오로라","어둠","투기","흐림","뇌운","파랑","파랑","먹구름","작열파","요마의 안개","폭풍","분화","맑음","맑음","맑음","맑음","맑음","극광","용핵","용핵","용핵","용핵","떼구름","떼구름","떼구름","떼구름","섭리","섭리","섭리","섭리","섭리","그림자바람","방전","연무","맑음","야수번개","번개파동","야수번개","섭리","번개","번개","신비","신비","비","맑음","비","맑음","사룡의 원념","사룡의 원념","맑음","조화","조화","시류","시류","시류","귀기","귀기","귀기","차원","차원","차원","호우","호우","미혹","미혹","신룡의 폭풍","신룡의 폭풍","호우","전선뇌우","번개","차원","맑음","쾌청","하얀 폭풍","하얀 폭풍","하얀 폭풍","환상","하얀 폭풍","달빛","달빛","달빛","달빛","붉은 달","붉은 불꽃 ","붉은 불꽃 ","붉은 불꽃 ","맑음","맑음","맑음","맑음","화염","해일","회오리","지진","푸른 봄날","푸른 봄날","푸른 봄날","난령류","푸른 봄날","끝없는 빛","폭풍","종말","종말","이상한 꿈","이상한 꿈","이상한 꿈","눈부신 하늘","눈부신 하늘","종말","종말","끝없는 빛","분화","종말","맑음","화속성풍","토속성풍","뇌속성풍","풍속성풍","유성우","기억난류","흐림","흐림","극광","극광","뇌운","불바람","환해류","결전","달모래먼지","자기장 폭풍","종말","별빛그림자","별빛그림자","별빛그림자","별빛그림자","별빛그림자","가상","마의 전당","마의 전당","마의 전당","종극","절망");

$zoneWeather = array('림사 로민사' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '림사 로민사 상층 갑판' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '림사 로민사 하층 갑판' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '중부 라노시아' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 70, 'Weather' => 2), array('Rate' => 80, 'Weather' => 5), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '저지 라노시아' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 70, 'Weather' => 2), array('Rate' => 80, 'Weather' => 5), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '동부 라노시아' => array(array('Rate' => 5, 'Weather' => 4), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 3), array('Rate' => 95, 'Weather' => 7), array('Rate' => 100, 'Weather' => 8)),
    '서부 라노시아' => array(array('Rate' => 10, 'Weather' => 4), array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 80, 'Weather' => 3), array('Rate' => 90, 'Weather' => 5), array('Rate' => 100, 'Weather' => 6)),
    '고지 라노시아' => array(array('Rate' => 30, 'Weather' => 1), array('Rate' => 50, 'Weather' => 2), array('Rate' => 70, 'Weather' => 3), array('Rate' => 80, 'Weather' => 4), array('Rate' => 90, 'Weather' => 9), array('Rate' => 100, 'Weather' => 10)),
    '그리다니아' => array(array('Rate' => 5, 'Weather' => 7), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 55, 'Weather' => 2), array('Rate' => 85, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '울다하 날 회랑' => array(array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '울다하 달 회랑 - 달 회랑' => array(array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '서부 다날란' => array(array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '중부 다날란' => array(array('Rate' => 15, 'Weather' => 11), array('Rate' => 55, 'Weather' => 1), array('Rate' => 75, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '동부 다날란' => array(array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 70, 'Weather' => 3), array('Rate' => 80, 'Weather' => 4), array('Rate' => 85, 'Weather' => 7), array('Rate' => 100, 'Weather' => 8)),
    '남부 다날란' => array(array('Rate' => 20, 'Weather' => 14), array('Rate' => 60, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '북부 다날란' => array(array('Rate' => 5, 'Weather' => 1), array('Rate' => 20, 'Weather' => 2), array('Rate' => 50, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '울다하' => array(array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '그리다니아 신시가지' => array(array('Rate' => 5, 'Weather' => 7), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 55, 'Weather' => 2), array('Rate' => 85, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '그리다니아 구시가지' => array(array('Rate' => 5, 'Weather' => 7), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 55, 'Weather' => 2), array('Rate' => 85, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '검은장막 숲 중부삼림' => array(array('Rate' => 5, 'Weather' => 9), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 55, 'Weather' => 2), array('Rate' => 85, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '검은장막 숲 동부삼림' => array(array('Rate' => 5, 'Weather' => 9), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 55, 'Weather' => 2), array('Rate' => 85, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '검은장막 숲 남부삼림' => array(array('Rate' => 5, 'Weather' => 4), array('Rate' => 10, 'Weather' => 10), array('Rate' => 25, 'Weather' => 9), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 70, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '검은장막 숲 북부삼림' => array(array('Rate' => 5, 'Weather' => 4), array('Rate' => 10, 'Weather' => 8), array('Rate' => 25, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 70, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '이슈가르드' => array(array('Rate' => 60, 'Weather' => 15), array('Rate' => 70, 'Weather' => 2), array('Rate' => 75, 'Weather' => 1), array('Rate' => 90, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '커르다스 중앙고지' => array(array('Rate' => 20, 'Weather' => 16), array('Rate' => 60, 'Weather' => 15), array('Rate' => 70, 'Weather' => 2), array('Rate' => 75, 'Weather' => 1), array('Rate' => 90, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '모르도나' => array(array('Rate' => 15, 'Weather' => 3), array('Rate' => 30, 'Weather' => 4), array('Rate' => 60, 'Weather' => 17), array('Rate' => 75, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '열두 신 대성당' => array(array('Rate' => 5, 'Weather' => 9), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 55, 'Weather' => 2), array('Rate' => 85, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '검은장막 숲 남부삼림 - 우르드의 샘' => array(array('Rate' => 100, 'Weather' => 20)),
    '시리우스 대등대 - 지하 1층' => array(array('Rate' => 100, 'Weather' => 3)),
    '남부 다날란 - 잔라크' => array(array('Rate' => 20, 'Weather' => 14), array('Rate' => 60, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '외지 라노시아' => array(array('Rate' => 30, 'Weather' => 1), array('Rate' => 50, 'Weather' => 2), array('Rate' => 70, 'Weather' => 3), array('Rate' => 85, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '사령함교: 제독실' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '늑대우리 부두' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 10)),
    '울부짖는 눈 석탑군' => array(array('Rate' => 100, 'Weather' => 28)),
    '얼음외투 대빙벽' => array(array('Rate' => 100, 'Weather' => 16)),
    '구름길' => array(array('Rate' => 100, 'Weather' => 3)),
    '안갯빛 마을' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 70, 'Weather' => 2), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '라벤더 안식처' => array(array('Rate' => 5, 'Weather' => 3), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 55, 'Weather' => 2), array('Rate' => 85, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '하늘잔 마루' => array(array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '울부짖는 눈 테두리' => array(array('Rate' => 100, 'Weather' => 28)),
    '쿠가네' => array(array('Rate' => 10, 'Weather' => 7), array('Rate' => 20, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '크리스타리움' => array(array('Rate' => 20, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 75, 'Weather' => 3), array('Rate' => 85, 'Weather' => 4), array('Rate' => 95, 'Weather' => 7), array('Rate' => 100, 'Weather' => 10)),
    '율모어' => array(array('Rate' => 10, 'Weather' => 6), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 45, 'Weather' => 3), array('Rate' => 85, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '울다하 날 회랑 - 울다하 비공정 승강장' => array(array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '울다하 달 회랑 - 관청 구역' => array(array('Rate' => 40, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '림사 로민사 상층 갑판 - 림사 로민사 비공정 승강장' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '에델바이스 상회' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 7)),
    '선착장 창고' => array(array('Rate' => 5, 'Weather' => 4), array('Rate' => 50, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 90, 'Weather' => 3), array('Rate' => 95, 'Weather' => 7), array('Rate' => 100, 'Weather' => 8)),
    '디아뎀 제도' => array(array('Rate' => 30, 'Weather' => 2), array('Rate' => 60, 'Weather' => 4), array('Rate' => 90, 'Weather' => 5), array('Rate' => 100, 'Weather' => 49)),
    '둔 스카 - 레이디 래들리아호' => array(array('Rate' => 100, 'Weather' => 1)),
    '고난호' => array(array('Rate' => 100, 'Weather' => 5)),
    '고지 드라바니아' => array(array('Rate' => 10, 'Weather' => 3), array('Rate' => 20, 'Weather' => 4), array('Rate' => 30, 'Weather' => 9), array('Rate' => 40, 'Weather' => 11), array('Rate' => 70, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '저지 드라바니아' => array(array('Rate' => 10, 'Weather' => 3), array('Rate' => 20, 'Weather' => 4), array('Rate' => 30, 'Weather' => 7), array('Rate' => 40, 'Weather' => 8), array('Rate' => 70, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '드라바니아 구름바다' => array(array('Rate' => 10, 'Weather' => 3), array('Rate' => 20, 'Weather' => 6), array('Rate' => 40, 'Weather' => 50), array('Rate' => 70, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '용의 둥지' => array(array('Rate' => 100, 'Weather' => 3)),
    '이딜샤이어' => array(array('Rate' => 10, 'Weather' => 3), array('Rate' => 20, 'Weather' => 4), array('Rate' => 30, 'Weather' => 7), array('Rate' => 40, 'Weather' => 8), array('Rate' => 70, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '아발라시아 구름바다' => array(array('Rate' => 30, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 70, 'Weather' => 3), array('Rate' => 80, 'Weather' => 4), array('Rate' => 90, 'Weather' => 5), array('Rate' => 100, 'Weather' => 49)),
    '아지스 라' => array(array('Rate' => 35, 'Weather' => 2), array('Rate' => 70, 'Weather' => 3), array('Rate' => 100, 'Weather' => 9)),
    '보이드의 방주 - 상부 갑판' => array(array('Rate' => 100, 'Weather' => 9)),
    '커르다스 서부고지' => array(array('Rate' => 20, 'Weather' => 16), array('Rate' => 60, 'Weather' => 15), array('Rate' => 70, 'Weather' => 2), array('Rate' => 75, 'Weather' => 1), array('Rate' => 90, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '차원의 틈' => array(array('Rate' => 100, 'Weather' => 79)),
    '이슈가르드 하층' => array(array('Rate' => 60, 'Weather' => 15), array('Rate' => 70, 'Weather' => 2), array('Rate' => 75, 'Weather' => 1), array('Rate' => 90, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '이슈가르드 상층' => array(array('Rate' => 60, 'Weather' => 15), array('Rate' => 70, 'Weather' => 2), array('Rate' => 75, 'Weather' => 1), array('Rate' => 90, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '피험세계 델타 V4.0' => array(array('Rate' => 100, 'Weather' => 79)),
    '랄거의 손길' => array(array('Rate' => 15, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 80, 'Weather' => 3), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 9)),
    '쿠가네' => array(array('Rate' => 10, 'Weather' => 7), array('Rate' => 20, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '기라바니아 변방지대' => array(array('Rate' => 15, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 80, 'Weather' => 3), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 9)),
    '기라바니아 산악지대' => array(array('Rate' => 10, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 75, 'Weather' => 3), array('Rate' => 85, 'Weather' => 4), array('Rate' => 95, 'Weather' => 5), array('Rate' => 100, 'Weather' => 11)),
    '기라바니아 호반지대' => array(array('Rate' => 20, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 80, 'Weather' => 3), array('Rate' => 90, 'Weather' => 4), array('Rate' => 100, 'Weather' => 10)),
    '홍옥해' => array(array('Rate' => 10, 'Weather' => 9), array('Rate' => 20, 'Weather' => 5), array('Rate' => 35, 'Weather' => 3), array('Rate' => 75, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '얀샤' => array(array('Rate' => 5, 'Weather' => 8), array('Rate' => 15, 'Weather' => 7), array('Rate' => 25, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '아짐 대초원' => array(array('Rate' => 5, 'Weather' => 6), array('Rate' => 10, 'Weather' => 5), array('Rate' => 17, 'Weather' => 7), array('Rate' => 25, 'Weather' => 4), array('Rate' => 35, 'Weather' => 3), array('Rate' => 75, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '시로가네' => array(array('Rate' => 10, 'Weather' => 7), array('Rate' => 20, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '에우레카: 아네모스 지대' => array(array('Rate' => 30, 'Weather' => 2), array('Rate' => 60, 'Weather' => 6), array('Rate' => 90, 'Weather' => 8), array('Rate' => 100, 'Weather' => 15)),
    '에우레카: 파고스 지대' => array(array('Rate' => 10, 'Weather' => 2), array('Rate' => 28, 'Weather' => 4), array('Rate' => 46, 'Weather' => 14), array('Rate' => 64, 'Weather' => 15), array('Rate' => 82, 'Weather' => 9), array('Rate' => 100, 'Weather' => 16)),
    '에우레카: 피로스 지대' => array(array('Rate' => 10, 'Weather' => 2), array('Rate' => 28, 'Weather' => 14), array('Rate' => 46, 'Weather' => 9), array('Rate' => 64, 'Weather' => 16), array('Rate' => 82, 'Weather' => 49), array('Rate' => 100, 'Weather' => 15)),
    '에우레카: 히다토스 지대' => array(array('Rate' => 12, 'Weather' => 2), array('Rate' => 34, 'Weather' => 8), array('Rate' => 56, 'Weather' => 17), array('Rate' => 78, 'Weather' => 10), array('Rate' => 100, 'Weather' => 15)),
    '차원의 틈' => array(array('Rate' => 100, 'Weather' => 77)),
    '열사암' => array(array('Rate' => 5, 'Weather' => 8), array('Rate' => 15, 'Weather' => 7), array('Rate' => 25, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '도마 도읍지' => array(array('Rate' => 5, 'Weather' => 8), array('Rate' => 15, 'Weather' => 7), array('Rate' => 25, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '망해루' => array(array('Rate' => 10, 'Weather' => 7), array('Rate' => 20, 'Weather' => 4), array('Rate' => 40, 'Weather' => 3), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '크리스타리움' => array(array('Rate' => 20, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 75, 'Weather' => 3), array('Rate' => 85, 'Weather' => 4), array('Rate' => 95, 'Weather' => 7), array('Rate' => 100, 'Weather' => 10)),
    '율모어 - 나무뿌리층' => array(array('Rate' => 10, 'Weather' => 6), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 45, 'Weather' => 3), array('Rate' => 85, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '레이크랜드' => array(array('Rate' => 20, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 75, 'Weather' => 3), array('Rate' => 85, 'Weather' => 4), array('Rate' => 95, 'Weather' => 7), array('Rate' => 100, 'Weather' => 10)),
    '콜루시아 섬' => array(array('Rate' => 10, 'Weather' => 6), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 4), array('Rate' => 45, 'Weather' => 3), array('Rate' => 85, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '아므 아랭' => array(array('Rate' => 45, 'Weather' => 2), array('Rate' => 60, 'Weather' => 3), array('Rate' => 70, 'Weather' => 11), array('Rate' => 80, 'Weather' => 14), array('Rate' => 100, 'Weather' => 1)),
    '일 메그' => array(array('Rate' => 10, 'Weather' => 7), array('Rate' => 20, 'Weather' => 4), array('Rate' => 35, 'Weather' => 3), array('Rate' => 45, 'Weather' => 10), array('Rate' => 60, 'Weather' => 1), array('Rate' => 100, 'Weather' => 2)),
    '라케티카 대삼림' => array(array('Rate' => 10, 'Weather' => 4), array('Rate' => 20, 'Weather' => 7), array('Rate' => 30, 'Weather' => 49), array('Rate' => 45, 'Weather' => 1), array('Rate' => 85, 'Weather' => 2), array('Rate' => 100, 'Weather' => 3)),
    '템페스트' => array(array('Rate' => 20, 'Weather' => 3), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '무원죄 왕관' => array(array('Rate' => 100, 'Weather' => 118)),
    '리예 메그' => array(array('Rate' => 100, 'Weather' => 4)),
    '창천 거리' => array(array('Rate' => 60, 'Weather' => 15), array('Rate' => 70, 'Weather' => 2), array('Rate' => 75, 'Weather' => 1), array('Rate' => 90, 'Weather' => 3), array('Rate' => 100, 'Weather' => 4)),
    '남부 보즈야 전선' => array(array('Rate' => 52, 'Weather' => 2), array('Rate' => 64, 'Weather' => 7), array('Rate' => 76, 'Weather' => 5), array('Rate' => 88, 'Weather' => 9), array('Rate' => 100, 'Weather' => 11)),
    '자트노르 고원' => array(array('Rate' => 60, 'Weather' => 2), array('Rate' => 70, 'Weather' => 7), array('Rate' => 80, 'Weather' => 5), array('Rate' => 90, 'Weather' => 9), array('Rate' => 100, 'Weather' => 15)),
    '어머니 크리스탈' => array(array('Rate' => 100, 'Weather' => 151)),
    '올드 샬레이안' => array(array('Rate' => 10, 'Weather' => 1), array('Rate' => 50, 'Weather' => 2), array('Rate' => 70, 'Weather' => 3), array('Rate' => 85, 'Weather' => 4), array('Rate' => 100, 'Weather' => 15)),
    '라자한' => array(array('Rate' => 10, 'Weather' => 4), array('Rate' => 25, 'Weather' => 7), array('Rate' => 40, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 3)),
    '라비린토스' => array(array('Rate' => 15, 'Weather' => 1), array('Rate' => 60, 'Weather' => 2), array('Rate' => 85, 'Weather' => 3), array('Rate' => 100, 'Weather' => 7)),
    '사베네어 섬' => array(array('Rate' => 10, 'Weather' => 4), array('Rate' => 20, 'Weather' => 7), array('Rate' => 25, 'Weather' => 8), array('Rate' => 40, 'Weather' => 1), array('Rate' => 80, 'Weather' => 2), array('Rate' => 100, 'Weather' => 3)),
    '갈레말드' => array(array('Rate' => 45, 'Weather' => 15), array('Rate' => 50, 'Weather' => 9), array('Rate' => 55, 'Weather' => 7), array('Rate' => 60, 'Weather' => 4), array('Rate' => 85, 'Weather' => 3), array('Rate' => 95, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '비탄의 바다' => array(array('Rate' => 15, 'Weather' => 49), array('Rate' => 30, 'Weather' => 148), array('Rate' => 100, 'Weather' => 2)),
    '울티마 툴레' => array(array('Rate' => 15, 'Weather' => 149), array('Rate' => 85, 'Weather' => 2), array('Rate' => 100, 'Weather' => 49)),
    '엘피스' => array(array('Rate' => 25, 'Weather' => 3), array('Rate' => 40, 'Weather' => 49), array('Rate' => 85, 'Weather' => 2), array('Rate' => 100, 'Weather' => 1)),
    '판데모니움 정문' => array(array('Rate' => 100, 'Weather' => 157)),
    '대회의실' => array(array('Rate' => 10, 'Weather' => 1), array('Rate' => 50, 'Weather' => 2), array('Rate' => 70, 'Weather' => 3), array('Rate' => 85, 'Weather' => 4), array('Rate' => 100, 'Weather' => 15)),
    '하늘의 끝' => array(array('Rate' => 100, 'Weather' => 160)),
    '지고천 거리' => array(array('Rate' => 5, 'Weather' => 15), array('Rate' => 25, 'Weather' => 2), array('Rate' => 65, 'Weather' => 1), array('Rate' => 80, 'Weather' => 3), array('Rate' => 90, 'Weather' => 4)));

?>
